VAT_RATE = 0.2
QUARTERLY_RENT = 9344.72
QUARTERLY_RENTOKILL = 463.31
QUARTERLY_WASTE_COLLECTION = 342.88
QUARTERLY_BIN_HIRE_EX_VAT = 62.0 / 1.2
YEARLY_DOOR_SECURITY = 470.0
MONTHLY_FOWLERS_ALARM = 75.0


MONTHLY_RENT = QUARTERLY_RENT / 3
MONTHLY_RENTOKILL = QUARTERLY_RENTOKILL / 3
MONTHLY_WASTE_COLLECTION = QUARTERLY_WASTE_COLLECTION / 3
MONTHLY_BIN_HIRE_EX_VAT = QUARTERLY_BIN_HIRE_EX_VAT / 3
MONTHLY_DOOR_SECURITY = YEARLY_DOOR_SECURITY / 12
